### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by salexzee** [TribalDev/tribal_blog#10]
The about page needs to be designed and styled.

**Comment by salexzee** [comment]
Anybody got any ideas on what we want to do with the about page? I was thinking we could talk about TribalDev at the top, then after that go into who makes up TribalDev. Just a thought. Ideas?

**Comment by dashtink** [comment]
I like the about page designs that have little divs on each person (kind of like this: https://teamtreehouse.com/about). And I think for the "what is TribalDev" section we need a mission statement or core values (I think DigitalOceans's core values are pretty cool: https://www.digitalocean.com/company/about/), or something along those lines, in addition to a general how we met and what we do.

**Comment by RoadBytes** [comment]
That's funny how the founder of treehouse also takes courses from treehouse, He must get a discount. 

I like how the mission statement is one sentence. Hopefully, won't be too hard to agree on something if we do the same. 

For digital ocean, that was cool how their social media is right on their name space. I say we make the front about us all look the same and have personal pages have set info like wikiesque. We could vote on a few must haves and the rest could be optional. 

Photo
Bio 
Skills
Personal portfolio
Blog links
Future hopes

**Comment by salexzee** [comment]
Personal portfolio should probably be your own website. Something that's all you and shows what you can do.

**Comment by jaeming** [comment]
With the bios, it could be nice to have a little fun with it and add one obviously made-up thing as the last sentence: 'nine-time runner-up for national laser-tag championship in the over 20's division'.

**Comment by jaeming** [comment]
I want mine to be, 'invented taco's.'

**Comment by salexzee** [comment]
That's a hilarious idea. +1 up vote

**Comment by salexzee** [comment]
Basically done.
