### ISSUE TITLE
Custom Icon Font

### ISSUE THREAD

**Issue by salexzee** [TribalDev/tribal_blog#13]
This isn't required, but it would damn sure be cool!

**Comment by jaeming** [comment]
Sounds cool. Just want to clarify by what is meant by 'custom'. Do we mean putting together a custom collection with some tool like fontello: http://fontello.com/
Or like, actually making our own icons?

I've mostly used font awesome for stuff in the past (which of course there is a gem for). Sometimes when I can't get what I want, I go for http://iconmonstr.com/ and download a png (they have svg too).

**Comment by salexzee** [comment]
By 'custom' I meant making our own. Either way is fine though.

**Comment by jaeming** [comment]
Sounds cool. I have no idea how to go about that but might be nice to learn.

**Comment by salexzee** [comment]
Grabbed some icons from icofonts and they should do us well.

**Comment by jaeming** [comment]
I have deployed the latest version. unfortunately the font-icons don't show. I followed on stack-overlfow solution but it did not work. Apparently it's something to do with Heroku though. I'll have to investigate further later on.
