### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by jaeming** [TribalDev/tribal_blog#18]
We need a way to upload and insert images.
I'm going to work on this a bit this weekend. We didn't want to put too much effort into the interface since it won't be public but on the other hand I think this is a good chance to try out some things and learn something new.

It might even be cool to have this as a micro SPA app here so you can upload images while working on a blog post and not have to worry about your post input disappearing. Could be fun to try in any case.

**Comment by jaeming** [comment]
The bare functionality is there! Yay!!!!!
Really. It's more steps than it seems. Just navigating the the AWS s3 console is as fun as playing with a pile of rocks.  Now, a few thoughts before we wrap this up. I've already asked for thoughts on UX. Now lets bring up resolution. What is the max resolution we want images on posts to have? We can always scale down if need be (but scale up looks bad), so what avg image size do you think will most often be uploaded?

**Comment by salexzee** [comment]
Since it's not a photography site, I would say we probably don't need over like 512px. Smaller images would probably be best for our needs. Plus they save on space and load time.

**Comment by jaeming** [comment]
I think I've found a happy medium and have also set up a thumb resolution for slightly smaller use. Might consider setting a tiny version as well but I can't think of a use-case for one.

**Comment by jaeming** [comment]
uploading multiple images to posts is now possible. Well close this for now. Feel free to re-open as needed.
