### ISSUE TITLE
categories

### ISSUE THREAD

**Issue by jaeming** [TribalDev/tribal_blog#19]
We'll definitely want categories(topics/tags, call it what you will). On the surface, this is an easy concept but it can get more complicated quickly. 

As the simplest solution, it could be an attribute of the post model. However I think since we'll likely be grouping posts by category, it'd be worthwhile to have it as it's own model with an association on Posts.

This brings up an important question:

Does a Post have only one category or multiple categories? 
For instance, a post may be about using React with Rails and therefore would justify more than one tag (Rails and React, or Ruby and JS, etc...).
If it's a many to many relationship, it'd be worthwhile having a join table I think.

A Post has many tags through categories and a tag has many post through categories.  

If we do go for multiple categories per post, I don't think we should let it get out of control. A category system becomes useless if you have like 20 tags on a single post in my opinion. 

Of course the other way is to limit us to only one category per post.  Any opinions on this?

**Comment by salexzee** [comment]
One category per post is a pretty simple thing to implement. Unless it's a tutorial on how to build a web application from start to finish, I don't think anything would really need more than one category.

**Comment by jaeming** [comment]
I'm happy to go with that. If anything it may help remind us to keep the scope of a tutorial in check.

**Comment by jaeming** [comment]
This is pretty much done. One minor bug is for editing/updating posts, the category shows as it's object instead of title. I can easily fix this if I use a separate view for the form rather than the partial (shared between create and update) but I want to look into a bit more first to see if I can figure the proper convention.  Also, thinking this who view might get replaced with a micro-spa app to facilitate the image uploads so this might all go away....

**Comment by jaeming** [comment]
Solved!
