### ISSUE TITLE
Editing Posts page doesn't show body for updating

### ISSUE THREAD

**Issue by ghost** [TribalDev/tribal_blog#21]
Sorry for the confusing title.  Welp, I posted on the blog, the one on Middlemanapp, and when I tried to edit it, I could change the title and categories, but there was a blank part right in the middle.  The page source of the edit page show's that my blog body is there, but it's not showing on the edit page on the view of the edit page:

![edit page without body](https://cloud.githubusercontent.com/assets/6753275/7985446/5f1176b0-0b03-11e5-8fc1-13f8a8beab17.png)
Edit View does not show blog body content

![source code of edit page showing there is body content](https://cloud.githubusercontent.com/assets/6753275/7985454/70ad3dd2-0b03-11e5-8b45-2ea8b977df62.png)
Inspecting element shows Edit View actually has body content in the HTML

Why is the visibility hidden?

**Comment by jaeming** [comment]
This is some crappy Heoku asset handling which has plagued every step of the way... 
I just kind of gave up and went with the less elegant but functional practice of throwing the necessary scripts in the public folder. The rich text text area should now be present.
