### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by salexzee** [TribalDev/tribal_blog#5]
People need to be able to comment on our blog posts.

**Comment by salexzee** [comment]
Need to have markdown formatting for the comments.

**Comment by jaeming** [comment]
We could consider using disqus for comments which might help keep down spam. 
Or if we do want to do out our commenting system, we could possibly do oauth and have people sign in through twitter, which might keep commenters more responsible (less mean).

**Comment by salexzee** [comment]
I like the second option.

**Comment by jaeming** [comment]
Agreed.

**Comment by jaeming** [comment]
This is just tied to users through devise at the moment. I'll set up omniauth with twitter for all users (not just commenters) so closing this one for now.
